title: PetPawCalc
description: Free calculators and tools for pet owners. Dog age, cat calories, pet costs and more.
url: "https://petpawcalc.com"
baseurl: ""

permalink: /blog/:slug/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "tools"
    values:
      layout: "tool"
      permalink: /tools/:name.html
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: /:name.html

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
